### ISSUE TITLE
ArgumentError: wrong number of arguments with ruby 3 and rails 7

### ISSUE THREAD

**Issue by anthonywoo** [grosser/ar_multi_threaded_transactional_tests#6]
I'm using ruby 3+ and postgres. Im trying to upgrade an app from rails 6 to rails 7.  I'm seeing the following new error in rails 7

```
ArgumentError: wrong number of arguments (given 6, expected 1..5)
    activerecord (7.0.8.6) lib/active_record/connection_adapters/abstract_adapter.rb:742:in `log'
    ar_multi_threaded_transactional_tests (0.6.0) lib/ar_multi_threaded_transactional_tests.rb:55:in `block in log'
    ar_multi_threaded_transactional_tests (0.6.0) lib/ar_multi_threaded_transactional_tests.rb:33:in `synchronize'
    ar_multi_threaded_transactional_tests (0.6.0) lib/ar_multi_threaded_transactional_tests.rb:55:in `log'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/postgresql_adapter.rb:781:in `exec_cache'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/postgresql_adapter.rb:747:in `execute_and_clear'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
    activerecord (7.0.8.6) lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
    activerecord (7.0.8.6) lib/active_record/querying.rb:54:in `_query_by_sql'
```

This appears to be happening because `log` has a [keyword arg](https://github.com/rails/rails/blob/v7.0.8.6/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L742) now in rails 7+  while the [log](https://github.com/grosser/ar_multi_threaded_transactional_tests/blob/v0.6.0/lib/ar_multi_threaded_transactional_tests.rb#L54) in this gem is converting it to a positional arg

**Comment by grosser** [comment]
try updating the gemfiles/*.lock to see if it reproduces, otherwise try with `log(...)` that might fix it

**Comment by anthonywoo** [comment]
I've confirmed using the `...` delegation syntax fixes the issue

I've submitted a PR with that change: https://github.com/grosser/ar_multi_threaded_transactional_tests/pull/7
